// <auto-generated />
using System;
using System.Collections.Generic;
using AtraccionesService.DataAcess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtraccionesService.DataAcess.Migrations.Sqlite
{
    [DbContext(typeof(SqliteAtraccionesDbContext))]
    [Migration("20261006233829_AddReportingIndexes")]
    partial class AddReportingIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.AttractionAvailabilityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId", "Date", "Time")
                        .IsUnique();

                    b.ToTable("attraction_availability", null, t =>
                        {
                            t.HasCheckConstraint("CK_availability_capacity", "Capacity >= 0 AND ReservedQuantity >= 0 AND ReservedQuantity <= Capacity");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FreeCancellation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RatingReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RatingScore")
                        .HasColumnType("REAL");

                    b.Property<string>("UrlApp")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlWeb")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity.Price#PriceValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("REAL")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductType");

                    b.ToTable("attractions", null, t =>
                        {
                            t.HasCheckConstraint("CK_attractions_product_type", "ProductType IN ('SINGLE_TICKET', 'GUIDED_TOUR', 'PACKAGE')");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.BadgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.InclusionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("includes", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("supported_languages", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("City");

                    b.HasIndex("Country");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.OperatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.PhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "AtraccionesService.DataAcess.Entities.Catalog.ReservationEntity.TotalPrice#PriceValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("REAL")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerEmail");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "Date");

                    b.ToTable("reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_reservations_status", "Status IN ('PENDING', 'CONFIRMED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_reservations_ticket_count", "TicketCount > 0");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.InventoryMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ReservationId");

                    b.ToTable("inventory_movements", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_movements_type", "MovementType IN ('HELD', 'CONFIRMED', 'RELEASED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HoldExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.HasIndex("ReservationId");

                    b.HasIndex("Status");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_orders_status", "Status IN ('PENDING_PAYMENT', 'PAID', 'FULFILLED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED')");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CreatedAt");

                    b.ToTable("order_events", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ServiceTime")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "AtraccionesService.DataAcess.Entities.Ecommerce.OrderItemEntity.UnitPrice#PriceValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("REAL")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_items_quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaymentSimulationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSimulationId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("payment_attempts", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentSimulationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSimulationId", "CreatedAt");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentSimulationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GatewayReference")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("payment_simulations", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_simulations_amount", "Amount > 0");

                            t.HasCheckConstraint("CK_payment_simulations_method", "PaymentMethod IN ('CARD', 'BANK_TRANSFER')");

                            t.HasCheckConstraint("CK_payment_simulations_status", "Status IN ('PENDING', 'AUTHORIZED', 'SETTLED', 'REJECTED', 'FAILED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED')");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PurchaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequestIdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ServiceTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "AtraccionesService.DataAcess.Entities.Ecommerce.PurchaseEntity.UnitPrice#PriceValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("REAL")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("AttractionId", "ServiceDate");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("CK_purchases_quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.RefundSimulationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentSimulationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PaymentSimulationId");

                    b.ToTable("refund_simulations", null, t =>
                        {
                            t.HasCheckConstraint("CK_refund_simulations_amount", "Amount > 0");

                            t.HasCheckConstraint("CK_refund_simulations_status", "Status IN ('PENDING', 'SETTLED', 'FAILED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodReference")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("OauthIssuer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OauthSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("OauthIssuer", "OauthSubject")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_status", "Status IN ('ACTIVE', 'LOCKED', 'DISABLED')");
                        });
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Technical.IdempotencyKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key", "Operation");

                    b.HasIndex("Issuer", "Subject", "Operation", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_keys", null, t =>
                        {
                            t.HasCheckConstraint("CK_idempotency_keys_status", "Status IN ('IN_PROGRESS', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("attraction_badges", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BadgeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttractionId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("attraction_badges");
                });

            modelBuilder.Entity("attraction_categories", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttractionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("attraction_categories");
                });

            modelBuilder.Entity("attraction_includes", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InclusionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttractionId", "InclusionId");

                    b.HasIndex("InclusionId");

                    b.ToTable("attraction_includes");
                });

            modelBuilder.Entity("attraction_languages", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttractionId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("attraction_languages");
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.AttractionAvailabilityEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.OperatorEntity", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.LocationEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany("Locations")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.PhotoEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany("Photos")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.ReservationEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.CustomerEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.CustomerEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.PurchaseEntity", null)
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.ReservationEntity", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEventEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderItemEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentAttemptEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentSimulationEntity", null)
                        .WithMany("Attempts")
                        .HasForeignKey("PaymentSimulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentEventEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentSimulationEntity", null)
                        .WithMany("Events")
                        .HasForeignKey("PaymentSimulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentSimulationEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PurchaseEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.CustomerEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.RefundSimulationEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentSimulationEntity", null)
                        .WithMany()
                        .HasForeignKey("PaymentSimulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.CustomerEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.UserEntity", null)
                        .WithOne("Customer")
                        .HasForeignKey("AtraccionesService.DataAcess.Entities.Identity.CustomerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.RolePermissionEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.RoleEntity", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.UserRoleEntity", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("attraction_badges", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.BadgeEntity", null)
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("attraction_categories", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("attraction_includes", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.InclusionEntity", null)
                        .WithMany()
                        .HasForeignKey("InclusionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("attraction_languages", b =>
                {
                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesService.DataAcess.Entities.Catalog.LanguageEntity", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Catalog.AttractionEntity", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.OrderEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Ecommerce.PaymentSimulationEntity", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.RoleEntity", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("AtraccionesService.DataAcess.Entities.Identity.UserEntity", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
