import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791348752205 implements MigrationInterface {
    name = 'InitialSchema1791348752205'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "operators" ("id" integer NOT NULL, "name" character varying(200) NOT NULL, CONSTRAINT "PK_3d02b3692836893720335a79d1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "badges" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, CONSTRAINT "UQ_9c91fc9c4a4ae01712baad1e9f6" UNIQUE ("name"), CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "includes" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, CONSTRAINT "UQ_dfb3270c37e51491f262cf4138c" UNIQUE ("name"), CONSTRAINT "PK_1e1048e8d572517793d777e7111" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supported_languages" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, CONSTRAINT "UQ_28ca26c268fc8e5de0ace692cb4" UNIQUE ("name"), CONSTRAINT "PK_096291688447e9253caf3e2a042" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attractions" ("id" uuid NOT NULL, "name" character varying(200) NOT NULL, "long_description" character varying(5000) NOT NULL, "duration" character varying(50) NOT NULL, "price_currency" character(3) NOT NULL, "price_amount" numeric(18,2) NOT NULL, "product_type" character varying(20) NOT NULL, "free_cancellation" boolean NOT NULL DEFAULT false, "operator_id" integer, "rating_review_count" integer, "rating_score" double precision, "url_web" character varying(500), "url_app" character varying(500), CONSTRAINT "CK_attractions_price" CHECK ("price_amount" > 0), CONSTRAINT "CK_attractions_product_type" CHECK ("product_type" IN ('SINGLE_TICKET', 'GUIDED_TOUR', 'PACKAGE')), CONSTRAINT "PK_d3d084e18c4d4f07de9c1521ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5207b13bb09eb0f0a40a37905f" ON "attractions" ("product_type") `);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "position" integer NOT NULL, "address" character varying(300) NOT NULL, "city" character varying(120) NOT NULL, "country" character(2) NOT NULL, "latitude" double precision, "longitude" double precision, "type" character varying(60), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1a9093eafe4afa3a5ee8ca096" ON "locations" ("city") `);
        await queryRunner.query(`CREATE INDEX "IDX_46e18f9b1e46a7720baaddf75a" ON "locations" ("country") `);
        await queryRunner.query(`CREATE TABLE "photos" ("id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "position" integer NOT NULL, "url" character varying(1000) NOT NULL, CONSTRAINT "PK_5220c45b8e32d49d767b9b3d725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attraction_availability" ("id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "date" date NOT NULL, "time" TIME NOT NULL, "capacity" integer NOT NULL, "reserved_quantity" integer NOT NULL DEFAULT '0', "version" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_availability_slot" UNIQUE ("attraction_id", "date", "time"), CONSTRAINT "CK_availability_capacity" CHECK ("capacity" >= 0 AND "reserved_quantity" >= 0 AND "reserved_quantity" <= "capacity"), CONSTRAINT "PK_b4d79318e97653a49de3a29a911" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservations" ("id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "date" date NOT NULL, "time" TIME NOT NULL, "ticket_count" integer NOT NULL, "total_currency" character(3) NOT NULL, "total_amount" numeric(18,2) NOT NULL, "customer_name" character varying(200) NOT NULL, "customer_email" character varying(254) NOT NULL, "status" character varying(20) NOT NULL, "cancellation_reason" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "CK_reservations_ticket_count" CHECK ("ticket_count" > 0), CONSTRAINT "CK_reservations_status" CHECK ("status" IN ('PENDING', 'CONFIRMED', 'CANCELLED')), CONSTRAINT "PK_da95cef71b617ac35dc5bcda243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_65bd81de685b6409e049d6aed9" ON "reservations" ("attraction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf047012a5362e7bbe9ffad3ea" ON "reservations" ("customer_email") `);
        await queryRunner.query(`CREATE INDEX "IDX_c42f5dcdd13d6e63ee44b4cb23" ON "reservations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f33547b81a81feeedb501df3ae" ON "reservations" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_52bb48bdce54d54e997a460fc2" ON "reservations" ("customer_id", "date") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL, "oauth_issuer" character varying(300) NOT NULL, "oauth_subject" character varying(300) NOT NULL, "email" character varying(254) NOT NULL, "status" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_users_identity" UNIQUE ("oauth_issuer", "oauth_subject"), CONSTRAINT "CK_users_status" CHECK ("status" IN ('ACTIVE', 'LOCKED', 'DISABLED')), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL, "user_id" uuid NOT NULL, "billing_name" character varying(200), "billing_email" character varying(254), "billing_address" character varying(300), "tax_id" character varying(30), "payment_method_reference" character varying(64), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "REL_11d81cd7be87b6f8865b0cf766" UNIQUE ("user_id"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL, "name" character varying(60) NOT NULL, "description" character varying(300), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission" character varying(100) NOT NULL, CONSTRAINT "PK_0167acb6e0ccfcf0c6c140cec4a" PRIMARY KEY ("role_id", "permission"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL, "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "assigned_by_user_id" uuid, "reason" character varying(500) NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_23ed6f04fe43066df08379fd03" ON "user_roles" ("user_id", "role_id") `);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL, "customer_id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "service_date" date NOT NULL, "service_time" TIME NOT NULL, "quantity" integer NOT NULL, "unit_price_currency" character(3) NOT NULL, "unit_price_amount" numeric(18,2) NOT NULL, "total_amount" numeric(18,2) NOT NULL, "request_idempotency_key" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "CK_purchases_quantity" CHECK ("quantity" > 0), CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b126c5c1c05fc81e93fc8d427" ON "purchases" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a90206d654e628742499a815e" ON "purchases" ("attraction_id", "service_date") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL, "customer_id" uuid NOT NULL, "purchase_id" uuid, "reservation_id" uuid, "status" character varying(30) NOT NULL, "currency" character(3) NOT NULL, "total_amount" numeric(18,2) NOT NULL, "hold_expires_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_1fea5a5872598eb9da87918c721" UNIQUE ("purchase_id"), CONSTRAINT "CK_orders_status" CHECK ("status" IN ('PENDING_PAYMENT', 'PAID', 'FULFILLED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED')), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_772d0ce0473ac2ccfa26060dbe" ON "orders" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_45bdd131d3c34179a7b0f37d15" ON "orders" ("reservation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c884e321f927d5b86aac7c8f9e" ON "orders" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL, "order_id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "availability_id" uuid NOT NULL, "service_date" date NOT NULL, "service_time" TIME NOT NULL, "quantity" integer NOT NULL, "unit_price_currency" character(3) NOT NULL, "unit_price_amount" numeric(18,2) NOT NULL, CONSTRAINT "CK_order_items_quantity" CHECK ("quantity" > 0), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_852d1cde77b25a512fb673bf00" ON "order_items" ("availability_id") `);
        await queryRunner.query(`CREATE TABLE "order_events" ("id" uuid NOT NULL, "order_id" uuid NOT NULL, "event_type" character varying(60) NOT NULL, "previous_status" character varying(30), "new_status" character varying(30) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_cc1b82b0fcf1be577d9d7ecbf8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94dcb98fcac804e1a0a357a56d" ON "order_events" ("order_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "payment_simulations" ("id" uuid NOT NULL, "order_id" uuid NOT NULL, "payment_method" character varying(20) NOT NULL, "status" character varying(30) NOT NULL, "amount" numeric(18,2) NOT NULL, "currency" character(3) NOT NULL, "gateway_reference" character varying(64) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "processed_at" TIMESTAMP WITH TIME ZONE, "failure_reason" character varying(300), CONSTRAINT "UQ_cd657120acb3e7ea477435263ad" UNIQUE ("gateway_reference"), CONSTRAINT "CK_payment_simulations_amount" CHECK ("amount" > 0), CONSTRAINT "CK_payment_simulations_method" CHECK ("payment_method" IN ('CARD', 'BANK_TRANSFER')), CONSTRAINT "CK_payment_simulations_status" CHECK ("status" IN ('PENDING', 'AUTHORIZED', 'SETTLED', 'REJECTED', 'FAILED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED')), CONSTRAINT "PK_b78cfb0305710579a2cd62789d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5eaa68c31f4328d3e34ea0001f" ON "payment_simulations" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d5b526eeaf85847dcf891c80f" ON "payment_simulations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_95b0899f8fe1946d1d1cae1d5d" ON "payment_simulations" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "payment_attempts" ("id" uuid NOT NULL, "payment_simulation_id" uuid NOT NULL, "attempt_number" integer NOT NULL, "status" character varying(30) NOT NULL, "response_code" character varying(10) NOT NULL, "response_message" character varying(300) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_payment_attempts_number" UNIQUE ("payment_simulation_id", "attempt_number"), CONSTRAINT "PK_a0d8a67c07a0fef98dfd20214e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_events" ("id" uuid NOT NULL, "payment_simulation_id" uuid NOT NULL, "event_type" character varying(60) NOT NULL, "payload" jsonb NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_9f1d16fc78b33e676940a32e8b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26283b55eef181e132df231fd7" ON "payment_events" ("payment_simulation_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL, "attraction_id" uuid NOT NULL, "availability_id" uuid NOT NULL, "quantity" integer NOT NULL, "movement_type" character varying(20) NOT NULL, "purchase_id" uuid, "reservation_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "CK_inventory_movements_type" CHECK ("movement_type" IN ('CONFIRMED', 'RELEASED', 'CANCELLED')), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d650dd3f833a3c4c862183d0f2" ON "inventory_movements" ("attraction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec034c59c14d03477374bdd1e9" ON "inventory_movements" ("availability_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca890ba14ee6a946dbbefb5cc7" ON "inventory_movements" ("purchase_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_df3b501fa2b39e52765a5f48e5" ON "inventory_movements" ("reservation_id") `);
        await queryRunner.query(`CREATE TABLE "audit_events" ("id" uuid NOT NULL, "actor_user_id" uuid, "actor_subject" character varying(300) NOT NULL, "action" character varying(100) NOT NULL, "resource_type" character varying(60) NOT NULL, "resource_id" character varying(100) NOT NULL, "reason" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_910f64d901a5c3e9878f0d4a407" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_497bb4f7c4c55db9749616cd2a" ON "audit_events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b827fe33511e95631908dab55" ON "audit_events" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE TABLE "idempotency_keys" ("id" uuid NOT NULL, "issuer" character varying(300) NOT NULL, "subject" character varying(300) NOT NULL, "operation" character varying(60) NOT NULL, "key" uuid NOT NULL, "request_hash" character varying(64) NOT NULL, "status" character varying(20) NOT NULL, "resource_id" uuid, "response_body" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_idempotency_identity" UNIQUE ("issuer", "subject", "operation", "key"), CONSTRAINT "CK_idempotency_keys_status" CHECK ("status" IN ('IN_PROGRESS', 'COMPLETED')), CONSTRAINT "PK_8ad20779ad0411107a56e53d0f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5fc0731b6752a8e9194fa265e" ON "idempotency_keys" ("expires_at") `);
        await queryRunner.query(`CREATE TABLE "attraction_categories" ("attraction_id" uuid NOT NULL, "category_id" integer NOT NULL, CONSTRAINT "PK_6e5226dde492a6b2384bcd6d944" PRIMARY KEY ("attraction_id", "category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b2cfd4654c92ee80e158c05a4" ON "attraction_categories" ("attraction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e8228b3ec5314a6715c434ebf" ON "attraction_categories" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "attraction_badges" ("attraction_id" uuid NOT NULL, "badge_id" integer NOT NULL, CONSTRAINT "PK_da733d8ccc672723ad6e4090aa4" PRIMARY KEY ("attraction_id", "badge_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70b04649d039b834153753bfbd" ON "attraction_badges" ("attraction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23215aabcef83cefcdadac244f" ON "attraction_badges" ("badge_id") `);
        await queryRunner.query(`CREATE TABLE "attraction_includes" ("attraction_id" uuid NOT NULL, "inclusion_id" integer NOT NULL, CONSTRAINT "PK_3131e805ebdea5c0b8b92844750" PRIMARY KEY ("attraction_id", "inclusion_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ed78f70dd64711264a0e000e0" ON "attraction_includes" ("attraction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec8e64e2f12db14a37960e0ce9" ON "attraction_includes" ("inclusion_id") `);
        await queryRunner.query(`CREATE TABLE "attraction_languages" ("attraction_id" uuid NOT NULL, "language_id" integer NOT NULL, CONSTRAINT "PK_aa57476698c5657d1e606b68208" PRIMARY KEY ("attraction_id", "language_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bc5c8f5f37a9286f6bb3bba5c" ON "attraction_languages" ("attraction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e61ca018c89600f96e5f82309e" ON "attraction_languages" ("language_id") `);
        await queryRunner.query(`ALTER TABLE "attractions" ADD CONSTRAINT "FK_3e97968d179e8e4f796816c30b6" FOREIGN KEY ("operator_id") REFERENCES "operators"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_453dc02b1d4e12e75db1472eafb" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_eb9cc9e46fcf43913e33eb067de" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attraction_availability" ADD CONSTRAINT "FK_5e93705836240483db70de79ec6" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_bfa1c28eba18c4493692faa8c0d" FOREIGN KEY ("assigned_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_6b126c5c1c05fc81e93fc8d427a" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_1fea5a5872598eb9da87918c721" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_45bdd131d3c34179a7b0f37d15b" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_events" ADD CONSTRAINT "FK_b33cbf9a59cbee112d94bcb59de" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_simulations" ADD CONSTRAINT "FK_5eaa68c31f4328d3e34ea0001f3" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" ADD CONSTRAINT "FK_3d4f0a049f6931f3bc72116557b" FOREIGN KEY ("payment_simulation_id") REFERENCES "payment_simulations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_events" ADD CONSTRAINT "FK_26d9a6288914fa9c178047a6926" FOREIGN KEY ("payment_simulation_id") REFERENCES "payment_simulations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_da4e1f7755a2ab9a8b7ddefaa4d" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attraction_categories" ADD CONSTRAINT "FK_1b2cfd4654c92ee80e158c05a4f" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_categories" ADD CONSTRAINT "FK_9e8228b3ec5314a6715c434ebf8" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_badges" ADD CONSTRAINT "FK_70b04649d039b834153753bfbd8" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_badges" ADD CONSTRAINT "FK_23215aabcef83cefcdadac244f1" FOREIGN KEY ("badge_id") REFERENCES "badges"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_includes" ADD CONSTRAINT "FK_9ed78f70dd64711264a0e000e06" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_includes" ADD CONSTRAINT "FK_ec8e64e2f12db14a37960e0ce99" FOREIGN KEY ("inclusion_id") REFERENCES "includes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_languages" ADD CONSTRAINT "FK_3bc5c8f5f37a9286f6bb3bba5c7" FOREIGN KEY ("attraction_id") REFERENCES "attractions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "attraction_languages" ADD CONSTRAINT "FK_e61ca018c89600f96e5f82309e2" FOREIGN KEY ("language_id") REFERENCES "supported_languages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attraction_languages" DROP CONSTRAINT "FK_e61ca018c89600f96e5f82309e2"`);
        await queryRunner.query(`ALTER TABLE "attraction_languages" DROP CONSTRAINT "FK_3bc5c8f5f37a9286f6bb3bba5c7"`);
        await queryRunner.query(`ALTER TABLE "attraction_includes" DROP CONSTRAINT "FK_ec8e64e2f12db14a37960e0ce99"`);
        await queryRunner.query(`ALTER TABLE "attraction_includes" DROP CONSTRAINT "FK_9ed78f70dd64711264a0e000e06"`);
        await queryRunner.query(`ALTER TABLE "attraction_badges" DROP CONSTRAINT "FK_23215aabcef83cefcdadac244f1"`);
        await queryRunner.query(`ALTER TABLE "attraction_badges" DROP CONSTRAINT "FK_70b04649d039b834153753bfbd8"`);
        await queryRunner.query(`ALTER TABLE "attraction_categories" DROP CONSTRAINT "FK_9e8228b3ec5314a6715c434ebf8"`);
        await queryRunner.query(`ALTER TABLE "attraction_categories" DROP CONSTRAINT "FK_1b2cfd4654c92ee80e158c05a4f"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_da4e1f7755a2ab9a8b7ddefaa4d"`);
        await queryRunner.query(`ALTER TABLE "payment_events" DROP CONSTRAINT "FK_26d9a6288914fa9c178047a6926"`);
        await queryRunner.query(`ALTER TABLE "payment_attempts" DROP CONSTRAINT "FK_3d4f0a049f6931f3bc72116557b"`);
        await queryRunner.query(`ALTER TABLE "payment_simulations" DROP CONSTRAINT "FK_5eaa68c31f4328d3e34ea0001f3"`);
        await queryRunner.query(`ALTER TABLE "order_events" DROP CONSTRAINT "FK_b33cbf9a59cbee112d94bcb59de"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_45bdd131d3c34179a7b0f37d15b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_1fea5a5872598eb9da87918c721"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_6b126c5c1c05fc81e93fc8d427a"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_bfa1c28eba18c4493692faa8c0d"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "attraction_availability" DROP CONSTRAINT "FK_5e93705836240483db70de79ec6"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_eb9cc9e46fcf43913e33eb067de"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_453dc02b1d4e12e75db1472eafb"`);
        await queryRunner.query(`ALTER TABLE "attractions" DROP CONSTRAINT "FK_3e97968d179e8e4f796816c30b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e61ca018c89600f96e5f82309e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bc5c8f5f37a9286f6bb3bba5c"`);
        await queryRunner.query(`DROP TABLE "attraction_languages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec8e64e2f12db14a37960e0ce9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ed78f70dd64711264a0e000e0"`);
        await queryRunner.query(`DROP TABLE "attraction_includes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23215aabcef83cefcdadac244f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70b04649d039b834153753bfbd"`);
        await queryRunner.query(`DROP TABLE "attraction_badges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e8228b3ec5314a6715c434ebf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b2cfd4654c92ee80e158c05a4"`);
        await queryRunner.query(`DROP TABLE "attraction_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5fc0731b6752a8e9194fa265e"`);
        await queryRunner.query(`DROP TABLE "idempotency_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b827fe33511e95631908dab55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_497bb4f7c4c55db9749616cd2a"`);
        await queryRunner.query(`DROP TABLE "audit_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df3b501fa2b39e52765a5f48e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca890ba14ee6a946dbbefb5cc7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec034c59c14d03477374bdd1e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d650dd3f833a3c4c862183d0f2"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26283b55eef181e132df231fd7"`);
        await queryRunner.query(`DROP TABLE "payment_events"`);
        await queryRunner.query(`DROP TABLE "payment_attempts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95b0899f8fe1946d1d1cae1d5d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d5b526eeaf85847dcf891c80f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eaa68c31f4328d3e34ea0001f"`);
        await queryRunner.query(`DROP TABLE "payment_simulations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94dcb98fcac804e1a0a357a56d"`);
        await queryRunner.query(`DROP TABLE "order_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_852d1cde77b25a512fb673bf00"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c884e321f927d5b86aac7c8f9e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45bdd131d3c34179a7b0f37d15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_772d0ce0473ac2ccfa26060dbe"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a90206d654e628742499a815e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b126c5c1c05fc81e93fc8d427"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23ed6f04fe43066df08379fd03"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52bb48bdce54d54e997a460fc2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f33547b81a81feeedb501df3ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c42f5dcdd13d6e63ee44b4cb23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf047012a5362e7bbe9ffad3ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65bd81de685b6409e049d6aed9"`);
        await queryRunner.query(`DROP TABLE "reservations"`);
        await queryRunner.query(`DROP TABLE "attraction_availability"`);
        await queryRunner.query(`DROP TABLE "photos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46e18f9b1e46a7720baaddf75a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1a9093eafe4afa3a5ee8ca096"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5207b13bb09eb0f0a40a37905f"`);
        await queryRunner.query(`DROP TABLE "attractions"`);
        await queryRunner.query(`DROP TABLE "supported_languages"`);
        await queryRunner.query(`DROP TABLE "includes"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "operators"`);
    }

}
